name: Check for differences for code-generation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-diff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Install dependencies
        run: go mod tidy

      - name: Run make generate
        run: make build

      - name: Check for differences
        run: |
          git diff --exit-code
